# Game setup
WIDTH = 1920
HEIGHT = 1080
FPS = 60
PYGAME_DISPLAY = 0

# Player default_settings
PLAYER_START_X = WIDTH / 2
PLAYER_START_Y = HEIGHT / 2
PLAYER_SIZE = 0.5
PLAYER_SPEED = 3
PLAYER_STARTING_HEALTH = 200
PLAYER_HIT_INTERVAL = 1

# Weapon default_settings
BULLET_LIFETIME = 750
SPLIT_SHOT_PRICE = 10

# Enemy default_settings
ENEMY_SIZE = 0.5
ENEMY_BASE_SPEED = 2
ENEMY_BASE_HEALTH = 100
ENEMY_BASE_DAMAGE = 50
ENEMY_BASE_SPAWN_COOLDOWN = 3000
ENEMY_BASE_WORTH = 1

# Level 0
SHOT_CD_0 = 20
BULLET_SIZE = 1.4
BULLET_SPEED = 40
